
INSERT INTO `business` (`id`, `type`, `name`, `description`, `phone_number`, `location`, `image`) VALUES
(1, 'Tradicional', 'POZOLERIA DOÑA SABI', 'Pozoleria Doña Sabi un excelente restaurante para venir a comer pozole, con un gran sabor tradicional, al igual un precio bastante conveniente', '+52 7221488122', 'https://maps.app.goo.gl/RD9W9yyz8GCk83XC9', '1700832368_pozole.webp'),
(2, 'Mexicana', 'TAQUERIA CARBAJAL´S', 'Quieres probar uno de los mejores tacos, ven y conoce la Taqueria Carbajal´s con unos tacos con excelente sabor', '+52 7221488122', 'https://maps.app.goo.gl/B62yVksbRdznDmca9', '1700832706_tacos.webp'),
(3, 'Tradicional', 'GALLETAS \"FRUTA DE HORNO\" CASA ARELLANO', 'Ven y conoce una de las principales tradiciones de Sultepec, las galletas de horno, las galletas tienen un gran sabor. ', '+52 7161480050', 'https://maps.app.goo.gl/oquKRRaqjDk6d2Cf7', '1700833043_galletas.jpg'),
(4, 'Mexicana', 'COCINA ECONOMICA DOÑA YOLA', 'Conoce la cocina econmica Doña Yola unos excelentes platillos que puedes disgustar ', '+52 7221488122', 'https://maps.app.goo.gl/SQ39KE1mnt5HeTjC7', '1700833487_chilaquiles-verdes-de-avena.jpg'),
(5, 'Oriental', 'RINCION DEL CHINO', 'Ven a consumir comida Oriental El Chino con una gran variedad de platillos que puedes venir a probar en familia', '+52 7225837321', 'https://maps.app.goo.gl/YqFKT4PiLCM2bbJf8', '1700833771_comida-china-cdmx.webp'),
(6, 'Mexicana', 'RESTAURANTE KARY', 'Ven a disgustar uno de los mejores platillos de la zona en el Resturante Kary con unos muy buenos platillos que puedes venir a probar', '+52 7161480514', 'https://maps.app.goo.gl/7uGhfW4ZVNrVKz8F9', '1700834163_kary.jpg'),
(7, 'Bebidas', 'MICHES EL TAMA', 'Ven a consumir bebidas en uno de los mejores bares del municipio de Sultepec donde puedes venir a divertirte con tus amigos y familiares', '+52 7225508963', 'https://maps.app.goo.gl/TXHiLskyMXAQuSzY8', '1700834554_MICHES_TAMA.webp');
